### ISSUE TITLE
Double standard in some names/استاندارد دوگانه در بعضی نام ها

### ISSUE THREAD

**Issue by yamin8000** [ahmadazizi/iran-cities#12]
به این پایگاه داده کمتر خرده ای میشه گرفت
ولی یکی از ناکارآمدی های بنیادی پایگاه داده های شهرهای ایران جریان استفاده از (ي و ك) عربی بوده و هست که در جستجو آزاردهنده است که این پایگاه داده این مشکلو نداره
ولی توی این پایگاه داده پی در پی دیده میشه اسم شهرهایی که پسوند آباد داره بعضی اوقات آباد نوشته شده بعضی اوقات اباد
بعضی اوقات آباد چسبانده شده بعضی اوقات جدا!
نمونه هاش:

> اصغرآباد

> علی اباد

> پارس آباد

من فک میکنم یکی از این حالت ها باید به عنوان یگانه استاندارد استفاده بشه و احتمالا این جریان توی فرهنگستان زبان و ادب فارسی پیش از این بررسی شده ولی به هر حال برای رفع این مشکل یکی از این حالت ها باید استفاده بشه
البته که در بعضی موارد استثنا هست که همون شکلی فعلیش مورد قبوله
مثلا
مهاباد، بهاباد، گناباد
یا حتی شهرِ آوا در خراسان شمالی که شهرآباد هم نوشته میشه

**Comment by ahmadazizi** [comment]
<div dir="rtl">
بله اینگونه موارد باید با استانداردگذاری حل بشه و این حداقل کاری هست که باید نهادهای متولی با همکاری هم انجام میدادن و استفاده میکردن


حتی توی اسامی انگلیسی هم این مشکل هست مثلا دوموردی که به یاد میارم یکی اصفهان هست که به شکل Esfahan, Isfahan , Esfehan نوشته میشه و یا مثلا قم که توی تابلوی بین شهری Qom  نوشته شده و توسط شهرداری یا جاهای دیگه Ghom استفاده میشه وگرنه به دلیل تغییرات زبان و وجود انواع شکل‌های گفتاری عادی و مرسوم هر اسم به چند جور مختلف میتونه نوشته بشه

</div>
