### ISSUE TITLE
بروز رسانی شهرستان های استان فارس

### ISSUE THREAD

**Issue by gholami-mohammad** [ahmadazizi/iran-cities#3]
در تقسیسم بندی جدید استان فارس دو شهرستان جدید در سال ۹۸ به استان فارس اضافه شده که میتونید آخرین آپدیتش رو از ویکی پدیا ببینید:

https://fa.wikipedia.org/wiki/%D9%81%D9%87%D8%B1%D8%B3%D8%AA_%D8%B4%D9%87%D8%B1%D8%B3%D8%AA%D8%A7%D9%86%E2%80%8C%D9%87%D8%A7%DB%8C_%D8%A7%D8%B3%D8%AA%D8%A7%D9%86_%D9%81%D8%A7%D8%B1%D8%B3

**Comment by ahmadazizi** [comment]
به روزرسانی انجام شد. لطفا بررسی نمایید
