### ISSUE TITLE
فایل مجتمع 

### ISSUE THREAD

**Issue by worldmohammad** [ahmadazizi/iran-cities#6]
فایل مجتمع و بهم متصل مطابق هر استان و شهرستان و.. رو در قالب اکسل یا اکسس ندارید؟؟؟

**Comment by ahmadazizi** [comment]
سلام
این پروژه فایل دیتا با فرمت سی.اس.وی و سکوئل ارایه می دهد و قابل تبدیل به سایر فرمت ها هست
