### ISSUE TITLE
import error Unknown collation

### ISSUE THREAD

**Issue by asadkhalili** [ahmadazizi/iran-cities#8]
سلام خسته نباشید.
تشکر بابت این بسته.
موقع ایمپورت در دیتابیس خطای زیر رو میده:

`Error
Static analysis:

1 errors were found during analysis.

A comma or a closing bracket was expected. (near "INVISIBLE" at position 421)
SQL query: Copy

CREATE TABLE `abadi` ( `id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `abadi_type` int DEFAULT NULL, `diag` varchar(50) DEFAULT NULL, `ostan` int DEFAULT NULL, `shahrestan` int DEFAULT NULL, `bakhsh` int DEFAULT NULL, `dehestan` int DEFAULT NULL, `amar_code` varchar(50) DEFAULT NULL, PRIMARY KEY (`id`), KEY `dehestan_idx` (`dehestan`), FULLTEXT KEY `name_txt` (`name`) /*!80000 INVISIBLE */ ) ENGINE=InnoDB AUTO_INCREMENT=98101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

MySQL said: Documentation

#1273 - Unknown collation: 'utf8mb4_0900_ai_ci'`

databse: mysql
Server type: MariaDB
Server version: 10.4.14-MariaDB
phpmyadmin: Version information: 5.0.3

**Comment by SepehrSepahi** [comment]
Open the SQL file with Notepad and replace **utf8mb4_0900_ai_ci** with **utf8mb4_general_ci**

Save the file and import it.

**Comment by keyone2693** [comment]
اگر موفق نشدید فایل های جیسانش اینجا هست
https://github.com/keyone2693/Iran.AspNet.CountryDivisions

**Comment by babakmajdy83** [comment]
after replacing utf8mb4_0900_ai_ci with utf8mb4_general_ci, we have this error too:

`Static analysis:

1 errors were found during analysis.

A comma or a closing bracket was expected. (near "INVISIBLE" at position 298)
SQL query:

CREATE TABLE `bakhsh` ( `id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `ostan` int DEFAULT NULL, `shahrestan` int DEFAULT NULL, `amar_code` varchar(50) DEFAULT NULL, PRIMARY KEY (`id`), KEY `idx_shahrestan` (`shahrestan`), FULLTEXT KEY `name_txt` (`name`) /*!80000 INVISIBLE */ ) ENGINE=InnoDB AUTO_INCREMENT=1100 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

MySQL said: Documentation

#1273 - Unknown collation: 'utf8mb4_0900_ai_ci'`

what is the solution?

**Comment by ahmadazizi** [comment]
با تشکر
اگر در ایمپورت فایل سکوئل مشکل دارید می تونید  از طریق ابزارهای مدیریتی فایل های سی اس وی را ایمپرت کنید

ظاهرا در خروجی نهایی سکوئل که اکسپرت گرفته شده
 collate utf8mb4_0900_ai_ci 
 درج شده که قاعدتا نباید مشکلی ایجاد کنه و درستش  
  utf8mb4_general_ci
 هست و و تا زمانی که اصلاح بشه میتونید  این دو را
 replace 
کنید.
